
import java.io.IOException;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import tareaencriptacion.DeterminarTipoCifrado;
import tareaencriptacion.Sustitucion;
import tareaencriptacion.Transposicion;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author David
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonTransposicion = new javax.swing.JButton();
        jTextFieldClave = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButtonSustitucion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonTransposicion.setText("EncriptarTransposicion");
        jButtonTransposicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTransposicionActionPerformed(evt);
            }
        });

        jTextFieldClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldClaveActionPerformed(evt);
            }
        });

        jLabel1.setText("Ingrese la clave");

        jButtonSustitucion.setText("EncriptarSustitucion");
        jButtonSustitucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSustitucionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonTransposicion, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(jButtonSustitucion, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
            .addGroup(layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldClave, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jTextFieldClave, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonTransposicion, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSustitucion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(99, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldClaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldClaveActionPerformed

    private void jButtonSustitucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSustitucionActionPerformed
        // TODO add your handling code here:
        String clave="";
        clave=jTextFieldClave.getText();
        if(clave.length()<1){
           JOptionPane.showMessageDialog(null, "Ingrese la clave"); 
        }
        else{
            
            
           
                Sustitucion s= new Sustitucion();
                try {
                    s.encriptar(clave);
                } catch (IOException ex) {
                    Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
                }
                //JOptionPane.showMessageDialog(null, "Archivo Encriptado Correctamente Sustitucion");
            
            DeterminarTipoCifrado det= new DeterminarTipoCifrado();
            Map m1= det.saveFrecuencias();
            
            int TipoCifrado= det.getTipoCifrado(m1);
            if(TipoCifrado==1){
               JOptionPane.showMessageDialog(null, "Archivo Encriptado Correctamente Por Transposicion"); 
            }
            else{
               JOptionPane.showMessageDialog(null, "Archivo Encriptado Correctamente Por Sustitucion"); 
            }
            
        }
    }//GEN-LAST:event_jButtonSustitucionActionPerformed

    private void jButtonTransposicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTransposicionActionPerformed
        // TODO add your handling code here:
        
        String clave="";
        clave=jTextFieldClave.getText();
        if(clave.length()<1){
           JOptionPane.showMessageDialog(null, "Ingrese la clave"); 
        }
        else{
            int numeroAleatorio =(int) (Math.random() * 2)+1;
            System.out.println("Numero Aleatorio:"+numeroAleatorio);
            
                Transposicion t=new Transposicion(clave);
                try {
                    t.Encriptar();
                   // JOptionPane.showMessageDialog(null, "Archivo Encriptado Correctamente Transposicion");
                } catch (IOException ex) {
                    Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
                }
            
            DeterminarTipoCifrado det= new DeterminarTipoCifrado();
            Map m1= det.saveFrecuencias();
            
            int TipoCifrado= det.getTipoCifrado(m1);
            if(TipoCifrado==1){
               JOptionPane.showMessageDialog(null, "Archivo Encriptado Correctamente Por Transposicion"); 
            }
            else{
               JOptionPane.showMessageDialog(null, "Archivo Encriptado Correctamente Por Sustitucion"); 
            }
            
        }
        
    }//GEN-LAST:event_jButtonTransposicionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSustitucion;
    private javax.swing.JButton jButtonTransposicion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextFieldClave;
    // End of variables declaration//GEN-END:variables
}
